baseURL = "https://blog.eleuther.ai/"
languageCode = "en-us"
title = "EleutherAI Blog"
theme = "eai-theme"
contentDir = "content-blog"
publishDir="public-blog"
[params]
    logo="EleutherAI"
    logo_image_url="images/eai_logo.png"
    contact_mail="contact@eleuther.ai"
    site_type="blog"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "solarized-light"
[menu]
  [[menu.main]]
    name = "Home"
    url = "https://eleuther.ai/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "https://eleuther.ai/about/"
    weight = 2
  [[menu.main]]
    name = "FAQ"
    url = "/faq/"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/"
    weight = 4
  [[menu.main]]
    name = "Publications"
    url = "https://eleuther.ai/publications/"
    weight = 5
  [[menu.main]]
    name = "Get Involved"
    url = "https://eleuther.ai/get-involved/"
    weight = 6
