baseURL = "http://example.org/"
languageCode = "en-us"
title = "Eleuther AI site"
theme = "eai-theme"
[params]
    description = "My site description"
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2
  [[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 3
  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 3
  [[menu.main]]
    name = "Get Involved"
    url = "/get-involved/"
    weight = 3
